options(repos = "https://cloud.r-project.org/")
library("metafor")
data("dat.bcg", package = "metafor")
dat <- escalc(measure = "RR", ai = tpos, bi = tneg, ci = cpos, 
              di = cneg, data = dat.bcg, append = TRUE)
k <- length(dat.bcg$trial)
dat.fm <- data.frame(study = factor(rep(1:k, each = 4)))
dat.fm$grp <- factor(rep(c("T", "T", "C", "C"), k), levels = c("T", "C"))
dat.fm$out <- factor(rep(c("+", "-", "+", "-"), k), levels = c("+", "-"))
dat.fm$freq <- with(dat.bcg, c(rbind(tpos, tneg, cpos, cneg)))
dat$a.random     <- ifelse(dat$alloc == "random",     1, 0)
dat$a.alternate  <- ifelse(dat$alloc == "alternate",  1, 0)
dat$a.systematic <- ifelse(dat$alloc == "systematic", 1, 0)
res <- rma(yi, vi, data = dat, slab = paste(author, year, sep=", "))
rcu <- cumul(res, order = order(dat$year))
forest(rcu, xlim = c(-6, 3), atransf = exp, 
       at = log(c(.10, .25, .5, 1, 2)))
text(-6, 15, "Author(s) and Year",     pos = 4, font = 2)
text( 3, 15, "Relative Risk [95% CI]", pos = 2, font = 2)