library("metafor")
data("dat.bcg", package = "metafor")
dat <- escalc(measure = "RR", ai = tpos, bi = tneg, ci = cpos, 
              di = cneg, data = dat.bcg, append = TRUE)
k <- length(dat.bcg$trial)
dat.fm <- data.frame(study = factor(rep(1:k, each = 4)))
dat.fm$grp <- factor(rep(c("T", "T", "C", "C"), k), levels = c("T", "C"))
dat.fm$out <- factor(rep(c("+", "-", "+", "-"), k), levels = c("+", "-"))
dat.fm$freq <- with(dat.bcg, c(rbind(tpos, tneg, cpos, cneg)))
dat$a.random     <- ifelse(dat$alloc == "random",     1, 0)
dat$a.alternate  <- ifelse(dat$alloc == "alternate",  1, 0)
dat$a.systematic <- ifelse(dat$alloc == "systematic", 1, 0)
res <- rma(yi, vi, data = dat, method = "FE")
radial(res, main = "Fixed-Effects Model")