---
title: "A space–time statistical climate model for hurricane intensification in the North Atlantic basin"
author:
    - name: Erik Fraza
      affiliation: Department of Geography, Florida State University
    - name: James B. Elsner
      affiliation: Department of Geography, Florida State University
    - name: Thomas H. Jagger
      affiliation: Department of Geography, Florida State University
date: "2. August 2016"
licenses:
  code: CC-BY-3.0
  data: CC-BY-3.0
  text: CC-BY-3.0
doi: 10.5194/ascmo-2-105-2016
abstract: "Climate influences on hurricane intensification are investigated by averaging hourly intensification rates over the period 1975–2014 in 8°x 8° latitude–longitude grid cells. The statistical effects of hurricane intensity and sea-surface temperature (SST), along with the climatic effects of El Niño–Southern Oscillation (ENSO), the North Atlantic Oscillation (NAO) and the Madden–Julian Oscillation (MJO), are quantified using a Bayesian hierarchical model fit to the averaged data. As expected, stronger hurricanes tend to have higher intensification rates, especially over the warmest waters. Of the three climate variables considered, the NAO has the largest effect on intensification rates after controlling for intensity and SST. The model shows an average increase in intensification rates of 0.18 [0.06, 0.31]ms^-1 h^-1 (95% credible interval) for every 1 standard deviation decrease in the NAO index. Weak trade winds associated with the negative phase of the NAO might result in less vertical wind shear and thus higher mean intensification rates."
output: html_document
---
<style>body{text-align:justify}</style>






```{r, include=FALSE}
list.files(pattern="mjomeiAnalysis.Rmd")
library(ggplot2)
library("dplyr")
library("latticeExtra")
load("mjoBestUse.RData")
Intensity = 33.0
Tracks.df = filter(Tracks.df, Int >= Intensity) 

```

```{r, include=FALSE}

fullData.df = load("best.use.2014.Rdata")
begin = 1975; end = 2014






```

```{r, include=FALSE}
library("rgdal")
ll = "+proj=longlat +ellps=WGS84"

Tracks.sdf = Tracks.df
coordinates(Tracks.sdf) = c("lon", "lat")
proj4string(Tracks.sdf) = CRS(ll)




```


```{r, include=FALSE}
library("raster")
r = raster(ncol = 10, nrow = 5, 
           xmn = -100, xmx = -20, 
           ymn = 10, ymx = 50)

Tracks.grid = rasterize(Tracks.sdf, r,
                        field = 'DIntDt',
                        fun = mean)

test = rasterToPolygons(Tracks.grid)
sid1=1675
Example.sdf = subset(Tracks.sdf, 
                     Sid == sid1 | 
                     Sid == 1677 |
                     Sid == 1683)
Example.grid = rasterize(Example.sdf, r, 
                         field = 'DIntDt',
                         fun = mean)
```

```{r, include=FALSE}
library("RColorBrewer")
library("rasterVis")
range(values(Example.grid), na.rm = TRUE)
rng = seq(0, 1.5, 1.5)
breaks = c(0, 0.25, 0.50, 0.75, 1.0, 1.25, 1.50)
cr = brewer.pal(9, "Purples")
cr = cr[-(1:3)]
vals = levelplot(Example.grid, margin = FALSE, 
          xlab = NULL, ylab = NULL, 
          col.regions = cr, at = rng, 
          colorkey = NULL,
          border = "white", border.lwd = 2, pretty=TRUE,
          par.settings = list(fontsize = list(text = 15)))
```


```{r, include=FALSE}
library("mapproj")
library("maptools")

outlines = as.data.frame(map("world", xlim = c(-100, -20), 
                             ylim = c(10, 50), 
                             plot = FALSE)[c("x", "y")],
                             color = "gray")
map = geom_path(aes(x, y), inherit.aes = FALSE, data = outlines, 
                alpha = .8, show_guide = FALSE, color = "blue")
ext = as.vector(extent(r))
boundaries = map("world", fill = TRUE, xlim = ext[1:2], 
                 ylim = ext[3:4], plot = FALSE)
IDs = sapply(strsplit(boundaries$names, ":"), function(x) x[1])
bPols <<- map2SpatialPolygons(boundaries, IDs = IDs,
                              proj4string = CRS(projection(r)))
```

```{r, message=FALSE, warning=FALSE, echo=FALSE, fig.cap="__Figure 1.__ Tracks and corresponding cells for three 2008 hurricanes: Gustav, Ike, and Omar. Each colored cell indicates at least one storm intensifies within its boundaries.", out.width=600}
#This chunk produces Figure 1 from the article

require(gridExtra)
require(sp)

Int2a.df = filter(Tracks.df, Sid == sid1)
Int2b.df = filter(Tracks.df, Sid == 1677)
Int2c.df = filter(Tracks.df, Sid == 1683)
holdera = data.frame(Int2a.df$lon, Int2a.df$lat)
holderb = data.frame(Int2b.df$lon, Int2b.df$lat)
holderc = data.frame(Int2c.df$lon, Int2c.df$lat)
linesa <<- SpatialLines(list(Lines(list(Line(holdera)),
                                 ID = 'Int2a.df$Sid')))
linesb <<- SpatialLines(list(Lines(list(Line(holderb)),
                                 ID = 'Int2b.df$Sid')))
linesc <<- SpatialLines(list(Lines(list(Line(holderc)),
                                 ID = 'Int2c.df$Sid')))


tracking = vals + 
  latticeExtra::layer(sp.polygons(bPols, col = gray(.8))) +
  latticeExtra::layer(sp.lines(linesa, lwd = 2, col = gray(.4))) + 
  latticeExtra::layer(sp.lines(linesb, lwd = 2, col = gray(.4))) + 
  latticeExtra::layer(sp.lines(linesc, lwd = 2, col = gray(.4))) +
  latticeExtra::layer(panel.text(-63.5, 27.5, 'Gustav', col = gray(.4))) +
  latticeExtra::layer(panel.text(-51, 16.5, 'Ike', col = gray(.4))) + 
  latticeExtra::layer(panel.text(-81.5, 16.25, 'Jane', col = gray(.4)))
plot(tracking)

```
